baseURL = "https://www.gorankatic.com/"
languageCode = "en"
title = "Goran Katic"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X


paginate = 15

enableRobotsTXT = true

disableHugoGeneratorInject = true

[markup.goldmark.renderer]
unsafe= true

hasCJKLanguage = true
summaryLength = 100

disqusShortname = ""  ## 是否开启disqus评论，不要和utteranc同时开启

[taxonomies]
tag = "tags"
category = "categories"


[permalinks]
    post = "/:slug/"

[author]
  name = "Goran Katic"

[params]
  author = "Goran Katic"
  subtitle = ""
  keywords = "Goran Katic,"
  description = "Goran Katic - connects people with the best things."
  busuanzi = false #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = false # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  # customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
 # customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = false  # 是否开启目录

